#!/bin/bash


#Check if we already have a folder with PSDTools name.
if [ -e ~/Desktop/PSDTools ]; then
    echo "Looks like you have a PSDTools folder at (~/Desktop)";
    echo "Remove it before using this script....";
    exit 1;
fi;

#Copy the whole folder and change to its location 
#(Gonna ease the file manipulation stuff.)
cp -r ../PSDTools ~/Desktop/PSDTools
cd ~/Desktop/PSDTools

#Change the #include SOMETHING in files, this is needed
#because we gonna hide them later.
sed -i "BACKUP" s/"\.\.\/Lib\/PSDHelpers.jsx"/"\.\.\/\.Lib\/PSDHelpers.jsx"/ PSDCutter/PSDCutterCore.jsx 
sed -i "BACKUP" s/"PSDCutterCore.jsx"/"\.PSDCutterCore.jsx"/ PSDCutter/PSDCutterGUI.jsx

#Remove all backups generated by sed.
find . -name "*BACKUP" -delete;

#Hide the files - Photoshop script submenu is very dumb and loads
#everything that's not hidden in the submenu.
mv ./Lib ./.Lib
mv PSDCutter/PSDCutter.jsx     PSDCutter/.PSDCutter.jsx
mv PSDCutter/PSDCutterCore.jsx PSDCutter/.PSDCutterCore.jsx

#Remove this file as well...
rm create_nice_script_folder_osx.sh

#COWTODO: Remove this line and replace to correct procedure when PSDIconMaker get done.
#Today we don't have any GUI front to PSDIconMaker so we just hide it for now.
mv ./PSDIconMaker ./.PSDIconMaker


#Show completion.
echo "Done...";
echo "You should have a nice and clean PSDTools folder at (~/Desktop)";
echo "Just copy it to your Photoshop scripts folder.";
